@startuml
'https://plantuml.com/class-diagram

class App{
    +{static}void main(String[] args)
    {static}void printFinal(ArrayList<Word>out)
    {static}String readFile(String path)
    {static}String[] splitString(String in)
    {static}ArrayList<Word> countWords(String[]in)
    {static}ArrayList<Word> sort(ArrayList<Word>words)
    {static}int checkforWord(ArrayList<Word>checkAgainst, String check)
}
class Word{
    -String word
    -int numOccurences
    +Word(String word, int numOccurrences)
    +void setNumOccurences(int numOccurences)
    +int getNumOccurences()
    +String getWord()
}
@enduml